//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract
{
    using System.Runtime.Serialization;
    using System.ServiceModel;



    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserRequest", Namespace = "http://schemas.datacontract.org/2004/07/Contract")]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Contract.UserBody BodyField;

        private Contract.RequestHead HeadField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contract.UserBody Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contract.RequestHead Head
        {
            get
            {
                return this.HeadField;
            }
            set
            {
                this.HeadField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserBody", Namespace = "http://schemas.datacontract.org/2004/07/Contract")]
    public partial class UserBody : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Contract.UserEntity UserField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contract.UserEntity User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestHead", Namespace = "http://schemas.datacontract.org/2004/07/Contract")]
    public partial class RequestHead : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CodeField;

        private long ExecutionTimeMsField;

        private string MessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExecutionTimeMs
        {
            get
            {
                return this.ExecutionTimeMsField;
            }
            set
            {
                this.ExecutionTimeMsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserEntity", Namespace = "http://schemas.datacontract.org/2004/07/Contract")]
    public partial class UserEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string EmailField;

        private int EntrepriseIDField;

        private int UserIDField;

        private string UsernameField;

        private string VilleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntrepriseID
        {
            get
            {
                return this.EntrepriseIDField;
            }
            set
            {
                this.EntrepriseIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville
        {
            get
            {
                return this.VilleField;
            }
            set
            {
                this.VilleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserResponse", Namespace = "http://schemas.datacontract.org/2004/07/Contract")]
    public partial class UserResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private Contract.RequestHead HeadField;

        private Contract.UserBody BodyField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Contract.RequestHead Head
        {
            get
            {
                return this.HeadField;
            }
            set
            {
                this.HeadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Contract.UserBody Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IUserService")]
public interface IUserService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/AddUser", ReplyAction = "http://tempuri.org/IUserService/AddUserResponse")]
    Contract.UserResponse AddUser(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/AddUser", ReplyAction = "http://tempuri.org/IUserService/AddUserResponse")]
    System.Threading.Tasks.Task<Contract.UserResponse> AddUserAsync(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/GetUser", ReplyAction = "http://tempuri.org/IUserService/GetUserResponse")]
    Contract.UserResponse GetUser(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/GetUser", ReplyAction = "http://tempuri.org/IUserService/GetUserResponse")]
    System.Threading.Tasks.Task<Contract.UserResponse> GetUserAsync(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/UpdateUser", ReplyAction = "http://tempuri.org/IUserService/UpdateUserResponse")]
    Contract.UserResponse UpdateUser(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/UpdateUser", ReplyAction = "http://tempuri.org/IUserService/UpdateUserResponse")]
    System.Threading.Tasks.Task<Contract.UserResponse> UpdateUserAsync(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/DeleteUser", ReplyAction = "http://tempuri.org/IUserService/DeleteUserResponse")]
    Contract.UserResponse DeleteUser(Contract.UserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUserService/DeleteUser", ReplyAction = "http://tempuri.org/IUserService/DeleteUserResponse")]
    System.Threading.Tasks.Task<Contract.UserResponse> DeleteUserAsync(Contract.UserRequest request);
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserServiceChannel : IUserService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserServiceClient : System.ServiceModel.ClientBase<IUserService>, IUserService
{

    public UserServiceClient()
    {
    }

    public UserServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public UserServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public Contract.UserResponse AddUser(Contract.UserRequest request)
    {
        return base.Channel.AddUser(request);
    }

    public System.Threading.Tasks.Task<Contract.UserResponse> AddUserAsync(Contract.UserRequest request)
    {
        return base.Channel.AddUserAsync(request);
    }

    public Contract.UserResponse GetUser(Contract.UserRequest request)
    {
        return base.Channel.GetUser(request);
    }

    public System.Threading.Tasks.Task<Contract.UserResponse> GetUserAsync(Contract.UserRequest request)
    {
        return base.Channel.GetUserAsync(request);
    }

    public Contract.UserResponse UpdateUser(Contract.UserRequest request)
    {
        return base.Channel.UpdateUser(request);
    }

    public System.Threading.Tasks.Task<Contract.UserResponse> UpdateUserAsync(Contract.UserRequest request)
    {
        return base.Channel.UpdateUserAsync(request);
    }

    public Contract.UserResponse DeleteUser(Contract.UserRequest request)
    {
        return base.Channel.DeleteUser(request);
    }

    public System.Threading.Tasks.Task<Contract.UserResponse> DeleteUserAsync(Contract.UserRequest request)
    {
        return base.Channel.DeleteUserAsync(request);
    }
}